# Generated by Django 5.1.3 on 2024-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_and_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Accepted', max_length=10),
        ),
    ]
