# Generated by Django 5.1.3 on 2024-11-09 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_unit_groups',
            field=models.ManyToManyField(to='job.unitgroup'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobseekerpreferences',
            name='job_seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker'),
        ),
        migrations.AddField(
            model_name='jobseekerpreferences',
            name='preferred_locations',
            field=models.ManyToManyField(related_name='job_seeker_preferences', to='accounts.location'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skill_levels',
            field=models.ManyToManyField(to='accounts.skilllevel'),
        ),
    ]
