# Generated by Django 5.1.3 on 2024-11-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_industry_options_industry_slug'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('issuing_organisation', models.CharField(max_length=50)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_or_qualification', models.CharField(choices=[('General Literate', 'General Literate'), ('Below SLC', 'Below SLC'), ('+2', '+2'), ('Bachelors', 'Bachelors'), ('Master & above', 'Master & above'), ('Pre-Diploma', 'Pre-Diploma'), ('Diploma', 'Diploma'), ('TLSC', 'TLSC'), ('No Education', 'No Education')], max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('year_of_completion', models.DateField(blank=True, null=True)),
                ('course_highlights', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skill_levels',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='availability',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full Time', max_length=50),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_locations',
            field=models.ManyToManyField(blank=True, to='accounts.location'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_salary_range_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_salary_range_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='remote_work_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='certifications',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='education',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='preferred_unit_groups',
            field=models.ManyToManyField(blank=True, to='job.unitgroup'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='languages',
            field=models.ManyToManyField(blank=True, to='accounts.language'),
        ),
        migrations.DeleteModel(
            name='JobSeekerPreferences',
        ),
        migrations.DeleteModel(
            name='SkillLevel',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skill_levels',
            field=models.CharField(choices=[('RPL', 'RPL'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='accounts.certification'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education',
            field=models.ManyToManyField(blank=True, to='accounts.education'),
        ),
    ]
