# Generated by Django 5.1.3 on 2024-11-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_certification_education_jobseekerskill_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerSkill',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-year_of_completion']},
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_seeker_skills', to='accounts.skill'),
        ),
    ]
