# Generated by Django 5.1.3 on 2024-11-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_jobseekerskill_alter_education_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerhistory',
            name='job_seeker',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='career_history',
            field=models.ManyToManyField(blank=True, related_name='job_seeker_career_history', to='accounts.careerhistory'),
        ),
    ]
