# Generated by Django 5.1.3 on 2024-11-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_careerhistory_job_seeker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerhistory',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['issue_date']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['year_of_completion']},
        ),
    ]
