# Generated by Django 5.1.3 on 2024-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_jobseeker_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Job Seeker', 'Job Seeker'), ('Wisher', 'Wisher'), ('Offerer', 'Offerer')], max_length=10),
        ),
    ]
