# Generated by Django 5.1.3 on 2024-12-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='availability',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full Time', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='preferred_salary_range_from',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='preferred_salary_range_to',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='remote_work_preference',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skill_levels',
            field=models.CharField(blank=True, choices=[('RPL', 'RPL'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('None', 'None')], default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='work_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
