# Generated by Django 5.1.3 on 2024-11-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_hirerequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='seeker_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
