# Generated by Django 5.1.3 on 2024-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_name_apprenticeshipcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minorgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submajorgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
